CREATE DATABASE BRAS_ANAMAX

USE BRAS_ANAMAX

CREATE TABLE TBUF(UF VARCHAR(2) PRIMARY KEY, NOMEUF VARCHAR(25),)
CREATE TABLE TBEQUIPE(SIGLA VARCHAR(3) PRIMARY KEY, EQUIPE VARCHAR(25), UF VARCHAR(2),)
CREATE TABLE TBRESULTADO(SIGLA VARCHAR(3) PRIMARY KEY, VITORIAS INT, EMPATES INT, DERROTAS INT,)

INSERT INTO TBUF(UF, NOMEUF) VALUES('AC','ACRE'), ('AL', 'ALAGOAS'), ('AP', 'AMAPÁ'), ('AM', 'AMAZONAS'), ('BA', 'BAHIA'), ('CE', 'CEARÁ'), ('DF', 'DISTRITO FEDERAL'),
('ES', 'ESPÍRITO SANTO'), ('GO', 'GOIÁS'), ('MA', 'MARANHÃO'), ('MT', 'MATO GROSSO'), ('MS', 'MATO GROSSO DO SUL'), ('MG', 'MINAS GERAIS'), ('PA', 'PARÁ'),
('PB', 'PARAÍBA'), ('PR', 'PARANÁ'), ('PE', 'PERNAMBUCO'), ('PI', 'PIAUÍ'), ('RJ', 'RIO DE JANEIRO'), ('RN', 'RIO GRANDE DO NORTE'),
('RS', 'RIO GRANDE DO SUL'), ('RO', 'RONDÔNIA'), ('RR', 'RORAIMA'), ('SC', 'SANTA CATARINA'), ('SP', 'SÃO PAULO'), ('SE', 'SERGIPE'), ('TO', 'TOCANTINS')

INSERT INTO TBEQUI(SIGLA, EQUIPE, UF) VALUES ('FLA', 'FLAMENGO', 'RJ'), ('SAN', 'SANTOS', 'SP'), ('PAL', 'PALMEIRAS', 'SP'), ('GRE', 'GRÊMIO', 'RS'), ('ATH', 'ATLÉTICO-PR', 'PR'),
('SP', 'SÃO PAULO', 'SP'), ('INT', 'INTERNACIONAL', 'RS')